package jv_package;

import com.mysql.jdbc.Connection;
import java.sql.*;
import javax.swing.JOptionPane;

public class frame1 extends javax.swing.JFrame {

    /**
     * Creates new form frame1
     */
    public frame1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AddBtn = new javax.swing.JButton();
        UpdateBtn = new javax.swing.JButton();
        DeleteBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        AddBtn.setText("ADD");
        AddBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddBtnActionPerformed(evt);
            }
        });

        UpdateBtn.setText("UPDATE");
        UpdateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateBtnActionPerformed(evt);
            }
        });

        DeleteBtn.setText("DELETE");
        DeleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(AddBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                .addGap(26, 26, 26)
                .addComponent(UpdateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(DeleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(111, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(UpdateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(AddBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(DeleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(122, 122, 122))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddBtnActionPerformed
        // TODO add your handling code here:
        String url = "jdbc:mysql://localhost:3306/the_gym?zeroDateTimeBehavior=convertToNull";
        String user = "root";
        String password = "";
        
        try {
            // Get connection to database
            Connection myConn = (Connection) DriverManager.getConnection(url, user, password);
            
            // Create Statement
            Statement myStmt = myConn.createStatement();
            
            // Execute Sql query
            String sql = "insert into tblMembers "
                       + " (Name, Surname, DOB, ID, Contact, MemberType) "
//                       + " values ('Lucas', 'Lebudi', '1995/12/09', '9512093948484', '0714049059', 'Annual:R200/year')";
//                       + " values ('Wayne', 'Rooney', '1996/11/18', '9611183948491', '0785636757', 'Monthly:R50/month')";
//                       + " values ('Cristiano', 'Ronaldo', '1997/08/08', '9708083948080', '0785539656', 'Monthly:R200/year')";
//                       + " values ('Ibra', 'Zlatan', '1998/05/09', '9805093948272', '0725634567', 'Monthly:R50/month')";
//                       + " values ('Sam', 'Thubane', '1999/01/17', '9901173948080', '0795636345', 'Monthly:R200/year')";
            + " values ('Eddie', 'Boy', '1999/01/17', '9901013948080', '0795636249', 'Monthly:R50/year')";
                       
                                
            myStmt.executeUpdate(sql);
            
            System.out.println("Insert Complete");
            JOptionPane.showMessageDialog(this, "Insert Complete");
        }
        catch (Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_AddBtnActionPerformed

    private void UpdateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateBtnActionPerformed
        // TODO add your handling code here:
        String url = "jdbc:mysql://localhost:3306/the_gym?zeroDateTimeBehavior=convertToNull";
        String user = "root";
        String password = "";
        
        try {
            // Get connection to database
            Connection myConn = (Connection) DriverManager.getConnection(url, user, password);
            
            // Create Statement
            Statement myStmt = myConn.createStatement();
            
            // Execute Sql query
            String sql = "update tblMembers "
                       + " set MemberType = 'Annual:R200/year'" // from 50/month to 200/year 
                       + " where MemberID = 3"; // CR7
            
            myStmt.executeUpdate(sql);
            
            System.out.println("Update Complete");
            JOptionPane.showMessageDialog(this, "Update Complete");
        }
        catch (Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_UpdateBtnActionPerformed

    private void DeleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteBtnActionPerformed
        // TODO add your handling code here:
        String url = "jdbc:mysql://localhost:3306/the_gym?zeroDateTimeBehavior=convertToNull";
        String user = "root";
        String password = "";
        
        try {
            // Get connection to database
            Connection myConn = (Connection) DriverManager.getConnection(url, user, password);
            
            // Create Statement
            Statement myStmt = myConn.createStatement();
            
            // Execute Sql query
            String sql = " delete from tblmembers where Surname = 'Kruger'";
            
            int rowsAffected = myStmt.executeUpdate(sql);
            
            System.out.println("Rows affected: " + rowsAffected);
            System.out.println("Delete Complete");
            JOptionPane.showMessageDialog(this, "Delete Complete");
        }
        catch (Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_DeleteBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frame1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddBtn;
    private javax.swing.JButton DeleteBtn;
    private javax.swing.JButton UpdateBtn;
    // End of variables declaration//GEN-END:variables
}
